version: "3.8"

services:
  proxy:
    container_name: proxy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
    restart: always
    networks:
      - proxy
    depends_on:
      - landing

  landing:
    container_name: landing
    image: landing:dev
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
