version: '3.8'

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
    restart: unless_stopped
    networks:
      - caddy
