version: '3.8'

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddyfile.dev:/etc/caddy/Caddyfile:rw
    restart: always
    networks:
      - caddy
    depends_on:
      - web

  web:
    container_name: web
    image: web:dev
    networks:
      - caddy

networks:
  caddy:
    name: caddy
    external: true
